CREATE OR REPLACE TABLE "Grouped_hashtags"  AS
SELECT "id", Oreder_date, Hashtags AS Original_hashtags,
    CASE
        WHEN Hashtags IN ('11profesibudoucnosti', '11profesíbudoucnosti') THEN '11profesibudoucnosti'
        WHEN Hashtags IN ('ai', 'aiイラスト', 'artificalinteligence', 'artificalintelligence', 'artificial_intelligence',                'artificialintelligence', 'inteligence', 'inteligenci', 'umela', 'umela_inteligence', 'umelaiinteligence', 'umelainteligence', 'umelainteligencia', 'umeleinteligenci', 'umelou', 'umělou', 'umělá', 'uměláinteligence', '') THEN 'AI'
        WHEN Hashtags IN ('babis', 'babišovazávěrečnářeč') THEN 'Babis'
        WHEN Hashtags IN ('audio', 'audioknihy', 'audioreklama') THEN 'audio'
        WHEN Hashtags IN ('bing', 'bingai', 'newbing', 'microsoftbing') THEN 'Bing'
        WHEN Hashtags IN ('microsoft365', 'microsoftdesigneri', 'microsoftteams', 'microsoft') THEN 'Microsoft'
        WHEN Hashtags IN ('nezamestnanost', 'nezaměstnanost') THEN 'nezamestnanost'
        WHEN Hashtags IN ('blindspotai') THEN 'Blindspot'
        WHEN Hashtags IN ('canva', 'canvacreate') THEN 'Canva'
        WHEN Hashtags IN ('chatbot', 'chatboti', 'chat') THEN 'chatbot'
        WHEN Hashtags IN ('breakingnews', 'novinky', 'news', 'newsroom') THEN 'News'
        WHEN Hashtags IN ('stablediffusion', 'stablediffusionart') THEN 'stablediffusion'
        WHEN Hashtags IN ('nvda', 'nvidia', 'nvidiaa2', 'nvidiadgxa100', 'nvidiadrive') THEN 'nvidia'
        WHEN Hashtags IN ('startup', 'startupjobs', 'startupjobscz', 'startups') THEN 'startup'
        WHEN Hashtags IN ('chatgpt', 'chatgpt3', 'chapgpt', 'chatgpt4', 'chatgtp', 'chatopenai', 'gpt', 'gpt3', 'gpt4', 'gtp', 'gptoday', 'gptzero', 'openaichatgpt', 'openai', 'radiogpt', 'сhatgpt') THEN 'ChatGPT'
        WHEN Hashtags IN ('coloursofostrava', 'coloursofostrava2022') THEN 'coloursofostrava'
        WHEN Hashtags IN ('cr', 'czech', 'czechia', 'cesko', 'czechrepublic', 'česko', 'česku') THEN 'Česko'
        WHEN Hashtags IN ('sci', 'sciencefiction', 'scifi', 'scifiart', 'scifireality') THEN 'scifi'
        WHEN Hashtags IN ('rusko', 'ruskyutoknaukrajinu', 'putin', 'putinwarcriminal', 'russia', 'russiancensorfiles', 'russiaukrainewar', 'vladimirputin') THEN 'Rusko'
        WHEN Hashtags IN ('roboagelab', 'robot', 'robot100', 'roboti', 'robotic', 'robotika', 'robotizace', 'robotspot') THEN 'robotizace'
        WHEN Hashtags IN ('regulace', 'regulation') THEN 'regulace'
        WHEN Hashtags IN ('dalle', 'dalle2') THEN 'DALL-E'
        WHEN Hashtags IN ('digital', 'digitalizace', 'digitalization', 'digitalni') THEN 'digitalizace'
        WHEN Hashtags IN ('ukraineunderattack', 'ukrainewarnews', 'ukrainewillwin', 'ukraine️', 'ukrainian', 'ukrajina') THEN 'Ukraine️'
        WHEN Hashtags IN ('fifa', 'fifa2022') THEN 'fifa'
        WHEN Hashtags IN ('fotografie', 'fotografování', 'obrazek', 'obrazku', 'obrazky', 'obrazkyai', 'photo', 'photooftheday', 'pictures') THEN 'obrazky'
        WHEN Hashtags IN ('prague', 'praha') THEN 'Praha'
        WHEN Hashtags IN ('future', 'budoucnost') THEN 'budoucnost'
        WHEN Hashtags IN ('podcast', 'podcasty', 'videopodcast') THEN 'podcasty'
        WHEN Hashtags IN ('podnikani', 'podnikatel', 'podnikatele', 'podnikavecesko', 'podnikání', 'ponikatel') THEN 'podnikani'
        WHEN Hashtags IN ('pisalek_ai', 'pisalek', 'pisalekai') THEN 'pisalek'
        WHEN Hashtags IN ('game', 'gamer', 'games', 'gaming', 'hra', 'hrac', 'hrani', 'hry', 'videogames', 'videohry') THEN 'game'
        WHEN Hashtags IN ('generativeai', 'generativniai', 'generovane', 'generovani') THEN 'generativniai'
        WHEN Hashtags IN ('horor', 'horror') THEN 'horor'
        WHEN Hashtags IN ('image', 'images') THEN 'image'
        WHEN Hashtags IN ('machinelearning', 'machinetranslation', 'ml', 'prediction', 'strojove', 'strojoveuceni', 'strojové') THEN 'machinelearning'
        WHEN Hashtags IN ('midjorney', 'midjourney', 'midjourney5', 'midjourneyai', 'midjourneyv5') THEN 'Midjourney'
        WHEN Hashtags IN ('program', 'programming', 'programovani') THEN 'programovani'
        WHEN Hashtags IN ('meta', 'metaverse', 'metaverzum') THEN 'metaverse'
        WHEN Hashtags IN ('prezident', 'volby', 'volby2023', 'volbyprezidentačr', 'voleb', 'prezident2023', 'prezidentskevolby', 'prezidentskévolby', 'prezidentskévolby2023', 'politika', 'generalpavel', 'general', '1kolo') THEN 'prezidentskevolby'
        WHEN Hashtags IN ('innovation', 'inovace') THEN 'inovace'
        WHEN Hashtags IN ('investice', 'investice2023', 'investicnitipy', 'investovani') THEN 'investice'
        WHEN Hashtags IN ('jazyk', 'jazyky') THEN 'jazyky'
        WHEN Hashtags IN ('kniha', 'milujemeknihy', 'cteninasbavi', 'knihazdarma', 'knihomol', 'knihy', 'knižní', 'komiks') THEN 'knihy'
        WHEN Hashtags IN ('virtualnirealita', 'vr') THEN 'virtualnirealita'
        WHEN Hashtags IN ('cybermonday', 'cyberpunk', 'cybersecurity') THEN 'cyber'
        WHEN Hashtags IN ('regulation', 'regulace') THEN 'regulace'
        WHEN Hashtags IN ('zdravotnictvi', 'zdravotnictví', 'telemedicina', 'ministrzdravi') THEN 'medecina'
        WHEN Hashtags IN ('elektromobil', 'elektromobily', 'elektronizace') THEN 'elektronizace'
        WHEN Hashtags IN ('energetika', 'energie', 'energii', 'energobot', 'energobotcz', 'enjoyelectric') THEN 'energie'
        WHEN Hashtags IN ('goog', 'google', 'googleads', 'googleai', 'googlebard', 'googlecloudplatform', 'googlecrowdsource', 'googleedu', 'googleio', 'googlemaps', 'googlestreetview', 'googlu') THEN 'Google'
        WHEN Hashtags IN ('image', 'ifotovideo', 'images') THEN 'images'
        WHEN Hashtags IN ('modernitechnologie', 'tech', 'tech4all', 'techguys', 'technews', 'technologie', 'technology', 'technologyenthusiast') THEN 'technologie'
        WHEN Hashtags IN ('telco', 'telecommunications', 'telekomunikace') THEN 'telekomunikace'
        ELSE Hashtags 
    END AS Grouped_hashtags, Hashtag_source
FROM "Hashtags_2021-2023"
order by hashtags asc;